AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  criar os recursos da lambda que faz a conexão com o dynamodb

Globals:
  Api:
    TracingEnabled: true
Resources:
  KeystrokeLevelModelQueryDatabase:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: KeystrokeLevelModelQueryDatabaseFunction
      CodeUri: KeystrokeLevelModelQueryDatabase
      Handler: com.keystrokelevelmodelquerydatabase.KeystrokeLevelModelQueryDatabaseApplication::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 1000
      Environment:
        Variables:
          DATABASE_NAME: KeystrokeLevelModel
          LAMBDA_ENVIRONMENT: LOCAL
          DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      Timeout: 60
      Tracing: Active
      Role: !GetAtt KeystrokeLevelModelDatabaseRole.Arn
