version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local:2.5.2
    container_name: dynamodb-local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - ".:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

networks:
  database:
    driver: bridge
